// DADOS DOS PERSONAGENS
export const personagens = [
  {
    nome: "Eduardo",
    frase: "Ele quer mover até da forma que me movo.",
    estado: "Vivo",
    classe: "Ocultista",
    grupo: ["Esquadrão Ômega", "Equipe Genesis"],
    ocupacao: ["Líder", "Piloto", "Agente"],
  },
  {
    nome: "Raoni",
    frase: "Como você disse, sem testemunhas.",
    estado: "Vivo",
    classe: "Especialista",
    grupo: ["Esquadrão Ômega", "Equipe Genesis"],
    ocupacao: ["Líder", "Piloto", "Caminhoneiro", "Agente"],
  },
{
    nome: "Maya",
    frase: "Por que eu não saí do carro?",
    estado: "Vivo",
    classe: "Especialista",
    grupo: ["Equipe Genesis", "Escola Paulaceia Desvairada"],
    ocupacao: ["Dançarina", "Atendente"],
  },
  {
    nome: "Ester",
    frase: "Se for para me matar, você e a puta da sua irmã vão queimar no inferno, seu esquisito.",
    estado: "Vivo",
    classe: "Combatente",
    grupo: ["Equipe Genesis", "Circo", "Gang de Motoqueiros"],
    ocupacao: ["Escoteiro", "Ginasta"],
  },
  {
    nome: "Jonatham",
    frase: "Me diz um número de 1 a 30.",
    estado: "Morto",
    classe: "Ocultista",
    grupo: ["Equipe Genesis"],
    ocupacao: ["Universitário"],
  },
  {
    nome: "Ricardo",
    frase: "Ahn? Você leu o livro?",
    estado: "Morto",
    classe: "Especialista",
    grupo: ["Equipe Genesis"],
    ocupacao: ["Escritor"],
  },
  {
    nome: "Palhaço",
    frase: "Quer ver uma mágica? Escolhe uma carta.",
    estado: "Vivo",
    classe: "Ocultista",
    grupo: ["Esquadrão Ômega", "Equipe Genesis", "Circo", "Entidade", "Paranormal"],
    ocupacao: ["Palhaço", "Agente"],
  },
  {
    nome: "Paulette",
    frase: "Oiiii rsrs.",
    estado: "Vivo",
    classe: "Ocultista",
    grupo: ["Equipe Genesis"],
    ocupacao: ["Nutricionista"],
  },
  {
    nome: "Lilian",
    frase: "",
    estado: "Vivo",
    classe: "Especialista",
    grupo: ["Ordo Realitas", "Equipe Genesis"],
    ocupacao: ["Blogueiro", "Agente", "Pesquisador Paranormal"],
  },
  {
    nome: "Santiago",
    frase: "Vocês são tipo heróis, né?... err, anti-heróis?",
    estado: "Vivo",
    classe: "Mundano",
    grupo: ["Equipe Genesis", "Ganiel", "Mercadinho dos Santos"],
    ocupacao: ["Dono de Mercado"],
  },
  {
    nome: "Kaio",
    frase: "E aí, do you wanna dance?",
    estado: "Desconhecido",
    classe: "Ocultista",
    grupo: ["Agente Solo", "Dupla de Sorte"],
    ocupacao: ["Freelancer Paranormal"],
  },
  {
    nome: "Leonardo",
    frase: "",
    estado: "Vivo",
    classe: "Combatente",
    grupo: ["Equipe Marotos", "Dupla de Sorte"],
    ocupacao: ["Freelancer Paranormal"],
  },
  {
    nome: "Luke",
    frase: "Au Au!",
    estado: "Morto",
    classe: "Animal",
    grupo: ["Criatura", "Paranormal"],
    ocupacao: ["Pet"],
  },
  {
    nome: "Detergente",
    frase: "Filho da puta! Filho da puta!",
    estado: "Vivo",
    classe: "Animal",
    grupo: ["Entidade", "Paranormal"],
    ocupacao: ["Pet"],
  },
  {
    nome: "Samuel",
    frase: "Que preguiça...",
    estado: "Morto",
    classe: "Combatente",
    grupo: ["Ganiel", "Culto de Genesis"],
    ocupacao: ["Braço direito", "Segurança"],
  },
  {
    nome: "Escritor",
    frase: "Moacir? Ele é a blasfêmia encarnada.",
    estado: "Morto",
    classe: "Especialista",
    grupo: ["Ganiel", "Culto de Genesis"],
    ocupacao: ["Escritor", "Cientista", "Praticante de Ocultismo", "Pesquisador Paranormal"],
  },
  {
    nome: "Eloá",
    frase: "Deus foi incompetente ao criar o mundo, mas eu não serei.",
    estado: "Amalgamado",
    classe: "Ocultista",
    grupo: ["Culto de Genesis"],
    ocupacao: ["Líder", "Ídolo", "Deus"],
  },
  {
    nome: "Morto",
    frase: "Eu? Morrer? Tenta de novo.",
    estado: "Vivo",
    classe: "Ocultista",
    grupo: ["Ordo Realitas", "Equipe Matheus"],
    ocupacao: ["Agente", "Pesquisador Paranormal"],
  },
  {
    nome: "Peste",
    frase: "",
    estado: "Vivo",
    classe: "Especialista",
    grupo: ["Ordo Realitas", "Equipe Matheus"],
    ocupacao: ["Agente", "Pesquisador Paranormal", "Cientista", "Engenheiro de Explosivos"],
  },
  {
    nome: "Matheus",
    frase: "Matheus! Pedra!",
    estado: "Vivo",
    classe: "Combatente",
    grupo: ["Ordo Realitas", "Equipe Matheus"],
    ocupacao: ["Matheus", "Agente"],
  },
  {
    nome: "Arlindo Barreto",
    frase: "Bem vindo à Ordo Realitas",
    estado: "Vivo",
    classe: "Especialista",
    grupo: ["Ordo Realitas", "Equipe Inexistência"],
    ocupacao: ["Líder", "Veríssimo", "Agente", "Palhaço"],    
  },
  {
    nome: "Kauane",
    frase: "Agora você me conheceu! Você não é mais sozinha.",
    estado: "Morto",
    classe: "Mundano",
    grupo: ["Escola Paulaceia Desvairada"],
    ocupacao: ["Dançarina"],    
  }
]